// Generated by gencpp from file mecanum_wheels_msgs/GetVariable.msg
// DO NOT EDIT!


#ifndef MECANUM_WHEELS_MSGS_MESSAGE_GETVARIABLE_H
#define MECANUM_WHEELS_MSGS_MESSAGE_GETVARIABLE_H

#include <ros/service_traits.h>


#include <mecanum_wheels_msgs/GetVariableRequest.h>
#include <mecanum_wheels_msgs/GetVariableResponse.h>


namespace mecanum_wheels_msgs
{

struct GetVariable
{

typedef GetVariableRequest Request;
typedef GetVariableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVariable
} // namespace mecanum_wheels_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mecanum_wheels_msgs::GetVariable > {
  static const char* value()
  {
    return "685a8058475bb3a593fd8f9319066e6a";
  }

  static const char* value(const ::mecanum_wheels_msgs::GetVariable&) { return value(); }
};

template<>
struct DataType< ::mecanum_wheels_msgs::GetVariable > {
  static const char* value()
  {
    return "mecanum_wheels_msgs/GetVariable";
  }

  static const char* value(const ::mecanum_wheels_msgs::GetVariable&) { return value(); }
};


// service_traits::MD5Sum< ::mecanum_wheels_msgs::GetVariableRequest> should match 
// service_traits::MD5Sum< ::mecanum_wheels_msgs::GetVariable > 
template<>
struct MD5Sum< ::mecanum_wheels_msgs::GetVariableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_wheels_msgs::GetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::GetVariableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_wheels_msgs::GetVariableRequest> should match 
// service_traits::DataType< ::mecanum_wheels_msgs::GetVariable > 
template<>
struct DataType< ::mecanum_wheels_msgs::GetVariableRequest>
{
  static const char* value()
  {
    return DataType< ::mecanum_wheels_msgs::GetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::GetVariableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mecanum_wheels_msgs::GetVariableResponse> should match 
// service_traits::MD5Sum< ::mecanum_wheels_msgs::GetVariable > 
template<>
struct MD5Sum< ::mecanum_wheels_msgs::GetVariableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_wheels_msgs::GetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::GetVariableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_wheels_msgs::GetVariableResponse> should match 
// service_traits::DataType< ::mecanum_wheels_msgs::GetVariable > 
template<>
struct DataType< ::mecanum_wheels_msgs::GetVariableResponse>
{
  static const char* value()
  {
    return DataType< ::mecanum_wheels_msgs::GetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::GetVariableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MECANUM_WHEELS_MSGS_MESSAGE_GETVARIABLE_H
