// Generated by gencpp from file mecanum_wheels_msgs/SetVariable.msg
// DO NOT EDIT!


#ifndef MECANUM_WHEELS_MSGS_MESSAGE_SETVARIABLE_H
#define MECANUM_WHEELS_MSGS_MESSAGE_SETVARIABLE_H

#include <ros/service_traits.h>


#include <mecanum_wheels_msgs/SetVariableRequest.h>
#include <mecanum_wheels_msgs/SetVariableResponse.h>


namespace mecanum_wheels_msgs
{

struct SetVariable
{

typedef SetVariableRequest Request;
typedef SetVariableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVariable
} // namespace mecanum_wheels_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mecanum_wheels_msgs::SetVariable > {
  static const char* value()
  {
    return "b9596f8691f82d6cddb450d38ac5e5af";
  }

  static const char* value(const ::mecanum_wheels_msgs::SetVariable&) { return value(); }
};

template<>
struct DataType< ::mecanum_wheels_msgs::SetVariable > {
  static const char* value()
  {
    return "mecanum_wheels_msgs/SetVariable";
  }

  static const char* value(const ::mecanum_wheels_msgs::SetVariable&) { return value(); }
};


// service_traits::MD5Sum< ::mecanum_wheels_msgs::SetVariableRequest> should match 
// service_traits::MD5Sum< ::mecanum_wheels_msgs::SetVariable > 
template<>
struct MD5Sum< ::mecanum_wheels_msgs::SetVariableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_wheels_msgs::SetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::SetVariableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_wheels_msgs::SetVariableRequest> should match 
// service_traits::DataType< ::mecanum_wheels_msgs::SetVariable > 
template<>
struct DataType< ::mecanum_wheels_msgs::SetVariableRequest>
{
  static const char* value()
  {
    return DataType< ::mecanum_wheels_msgs::SetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::SetVariableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mecanum_wheels_msgs::SetVariableResponse> should match 
// service_traits::MD5Sum< ::mecanum_wheels_msgs::SetVariable > 
template<>
struct MD5Sum< ::mecanum_wheels_msgs::SetVariableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mecanum_wheels_msgs::SetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::SetVariableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecanum_wheels_msgs::SetVariableResponse> should match 
// service_traits::DataType< ::mecanum_wheels_msgs::SetVariable > 
template<>
struct DataType< ::mecanum_wheels_msgs::SetVariableResponse>
{
  static const char* value()
  {
    return DataType< ::mecanum_wheels_msgs::SetVariable >::value();
  }
  static const char* value(const ::mecanum_wheels_msgs::SetVariableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MECANUM_WHEELS_MSGS_MESSAGE_SETVARIABLE_H
