// Generated by gencpp from file mecanum_wheels_msgs/WheelsCmdStamped.msg
// DO NOT EDIT!


#ifndef MECANUM_WHEELS_MSGS_MESSAGE_WHEELSCMDSTAMPED_H
#define MECANUM_WHEELS_MSGS_MESSAGE_WHEELSCMDSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mecanum_wheels_msgs
{
template <class ContainerAllocator>
struct WheelsCmdStamped_
{
  typedef WheelsCmdStamped_<ContainerAllocator> Type;

  WheelsCmdStamped_()
    : header()
    , vel_left_front(0.0)
    , vel_right_front(0.0)
    , vel_left_rear(0.0)
    , vel_right_rear(0.0)
    , theta(0.0)  {
    }
  WheelsCmdStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel_left_front(0.0)
    , vel_right_front(0.0)
    , vel_left_rear(0.0)
    , vel_right_rear(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _vel_left_front_type;
  _vel_left_front_type vel_left_front;

   typedef float _vel_right_front_type;
  _vel_right_front_type vel_right_front;

   typedef float _vel_left_rear_type;
  _vel_left_rear_type vel_left_rear;

   typedef float _vel_right_rear_type;
  _vel_right_rear_type vel_right_rear;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> const> ConstPtr;

}; // struct WheelsCmdStamped_

typedef ::mecanum_wheels_msgs::WheelsCmdStamped_<std::allocator<void> > WheelsCmdStamped;

typedef boost::shared_ptr< ::mecanum_wheels_msgs::WheelsCmdStamped > WheelsCmdStampedPtr;
typedef boost::shared_ptr< ::mecanum_wheels_msgs::WheelsCmdStamped const> WheelsCmdStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mecanum_wheels_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mecanum_wheels_msgs': ['/home/sis/catkin_ws/src/mecanum_wheels/catkin_ws/src/mecanum_wheels_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "601fa5a1cb9c2a11f41fde1a99471d43";
  }

  static const char* value(const ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x601fa5a1cb9c2a11ULL;
  static const uint64_t static_value2 = 0xf41fde1a99471d43ULL;
};

template<class ContainerAllocator>
struct DataType< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mecanum_wheels_msgs/WheelsCmdStamped";
  }

  static const char* value(const ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 vel_left_front\n\
float32 vel_right_front\n\
float32 vel_left_rear\n\
float32 vel_right_rear\n\
float32 theta\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel_left_front);
      stream.next(m.vel_right_front);
      stream.next(m.vel_left_rear);
      stream.next(m.vel_right_rear);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelsCmdStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mecanum_wheels_msgs::WheelsCmdStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel_left_front: ";
    Printer<float>::stream(s, indent + "  ", v.vel_left_front);
    s << indent << "vel_right_front: ";
    Printer<float>::stream(s, indent + "  ", v.vel_right_front);
    s << indent << "vel_left_rear: ";
    Printer<float>::stream(s, indent + "  ", v.vel_left_rear);
    s << indent << "vel_right_rear: ";
    Printer<float>::stream(s, indent + "  ", v.vel_right_rear);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MECANUM_WHEELS_MSGS_MESSAGE_WHEELSCMDSTAMPED_H
